syntax = "proto3";
package geopki;

option go_package = "pkg/comm";

message SignedConsistencyHead {
  bytes RootHash = 1;
  uint64 Timestamp = 2;
  uint64 Size = 3;

  bytes Signature = 4;
}

message SignedMapHead {
  bytes RootHash = 1;
  uint64 Timestamp = 2;

  bytes Signature = 3;
}

// a node corresponds to a database row
message Node {
  // the 52 bits of the xy bit string
  uint64 XYBitString = 1;
  uint32 XYBitStringLen = 2;

  // the 15 bits of the z bit string
  uint32 ZBitString = 3;
  uint32 ZBitStringLen = 4;

  // optional hash values for and all children
  optional bytes XYLeftChildHash = 5;
  optional bytes XYRightChildHash = 6;
  optional bytes ZLeftChildHash = 7;
  optional bytes ZRightChildHash = 8;

  // (optional) a list of certificate hashes
  repeated bytes CertificateHashes = 9;
}

message Response {
  SignedConsistencyHead SignedConsistencyHead = 1;
  SignedMapHead SignedMapHead = 2;

  repeated Node Nodes = 3;

  repeated bytes Certificates = 4;
}